services:
  zookeeper:
    image: bitnami/zookeeper:3.9-debian-12
    ports:
      - "2181:2181"
    networks:
      - app-network
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper:2888:3888
  kafka:
    image: bitnami/kafka:3.3-debian-12
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL_LISTENER://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL_LISTENER://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:29092"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cassandra:
    image: bitnami/cassandra:5.0-debian-12
    environment:
      - CASSANDRA_CLUSTER_NAME=dev-cassandra-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_AUTHENTICATOR=AllowAllAuthenticator
      - CASSANDRA_AUTHORIZER=AllowAllAuthorizer
      - CASSANDRA_ENABLE_REMOTE_CONNECTIONS=true
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME:-cassandra}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD:-cassandra}

    ports:
      - "9042:9042"
    volumes:
    - cassandra-data:/bitnami/cassandra
    - ./init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 2s
      retries: 100
    restart: unless-stopped

volumes:
  cassandra-data:

networks:
  app-network:
    driver: bridge
