global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9092']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['host.docker.internal:9042']
